disabled_rules:
  - identifier_name
  - nesting
  - function_parameter_count

opt_in_rules:
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma

included:
    - Gister
  
force_cast: warning

force_try:
  severity: warning

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 500
  error: 800

large_tuple:
   - 3
   - 4
   
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 30
    error: 35
  excluded: iPhone # excluded via string
reporter: "xcode"